package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"
	"learning-server/entity"
	"learning-server/graph/models"
	"learning-server/internal/services"
)

// User is the resolver for the user field.
func (r *answerResolver) User(ctx context.Context, obj *entity.Answer) (*entity.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// CreatedBy is the resolver for the createdBy field.
func (r *examResolver) CreatedBy(ctx context.Context, obj *entity.Exam) (*entity.User, error) {
	panic(fmt.Errorf("not implemented: CreatedBy - createdBy"))
}

// UpdatedBy is the resolver for the updatedBy field.
func (r *examResolver) UpdatedBy(ctx context.Context, obj *entity.Exam) (*entity.User, error) {
	panic(fmt.Errorf("not implemented: UpdatedBy - updatedBy"))
}

// DeletedBy is the resolver for the deletedBy field.
func (r *examResolver) DeletedBy(ctx context.Context, obj *entity.Exam) (*entity.User, error) {
	panic(fmt.Errorf("not implemented: DeletedBy - deletedBy"))
}

// CreateExam is the resolver for the createExam field.
func (r *mutationResolver) CreateExam(ctx context.Context, input entity.ExamInput) (*entity.Exam, error) {
	return services.CreateExam(ctx, input)
}

// AddQuestionIntoExam is the resolver for the addQuestionIntoExam field.
func (r *mutationResolver) AddQuestionIntoExam(ctx context.Context, id string, input entity.QuestionInput) (*entity.Exam, error) {
	return services.AddQuestionIntoExam(ctx, id, input)
}

// QuestionTemplates is the resolver for the questionTemplates field.
func (r *queryResolver) QuestionTemplates(ctx context.Context) ([]*entity.QuestionTemplate, error) {
	return services.ListQuestionTemplates(ctx)
}

// Exams is the resolver for the exams field.
func (r *queryResolver) Exams(ctx context.Context) ([]*entity.Exam, error) {
	return services.ListExam(ctx)
}

// FindExam is the resolver for the findExam field.
func (r *queryResolver) FindExam(ctx context.Context, id string) (*entity.Exam, error) {
	return services.FindExamById(ctx, id)
}

// CreatedBy is the resolver for the createdBy field.
func (r *questionResolver) CreatedBy(ctx context.Context, obj *entity.Question) (*entity.User, error) {
	panic(fmt.Errorf("not implemented: CreatedBy - createdBy"))
}

// UpdatedBy is the resolver for the updatedBy field.
func (r *questionResolver) UpdatedBy(ctx context.Context, obj *entity.Question) (*entity.User, error) {
	panic(fmt.Errorf("not implemented: UpdatedBy - updatedBy"))
}

// DeletedBy is the resolver for the deletedBy field.
func (r *questionResolver) DeletedBy(ctx context.Context, obj *entity.Question) (*entity.User, error) {
	panic(fmt.Errorf("not implemented: DeletedBy - deletedBy"))
}

// Media is the resolver for the media field.
func (r *questionInputResolver) Media(ctx context.Context, obj *entity.QuestionInput, data *models.MediaInput) error {
	return nil
}

// Blocks is the resolver for the blocks field.
func (r *questionInputResolver) Blocks(ctx context.Context, obj *entity.QuestionInput, data []*models.BlockInput) error {
	return nil
}

// Options is the resolver for the options field.
func (r *questionInputResolver) Options(ctx context.Context, obj *entity.QuestionInput, data []*models.BlockInput) error {
	panic(fmt.Errorf("not implemented: Options - options"))
}

// CorrectOption is the resolver for the correctOption field.
func (r *questionInputResolver) CorrectOption(ctx context.Context, obj *entity.QuestionInput, data []*models.BlockInput) error {
	panic(fmt.Errorf("not implemented: CorrectOption - correctOption"))
}

// Answer returns AnswerResolver implementation.
func (r *Resolver) Answer() AnswerResolver { return &answerResolver{r} }

// Exam returns ExamResolver implementation.
func (r *Resolver) Exam() ExamResolver { return &examResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Question returns QuestionResolver implementation.
func (r *Resolver) Question() QuestionResolver { return &questionResolver{r} }

// QuestionInput returns QuestionInputResolver implementation.
func (r *Resolver) QuestionInput() QuestionInputResolver { return &questionInputResolver{r} }

type answerResolver struct{ *Resolver }
type examResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type questionResolver struct{ *Resolver }
type questionInputResolver struct{ *Resolver }
