scalar ObjectID
scalar DateTime

type GroupQuestion {
  _id: ObjectID!
  title: String
  description: String
  thumbnailUrl: String
  questions: [Question]
  answers: [Answer]
  anyTime: Boolean
  startAt: DateTime
  endAt: DateTime
  publishedAt: DateTime
  createdAt: DateTime
  createdBy: User
  updatedAt: DateTime
  deletedAt: DateTime
}

type Answer {
  _id: ObjectID!
  user: User
  lock: Boolean
  questions: [Question]
  startAt: DateTime
  endAt: DateTime
  publishedAt: DateTime
  createdAt: DateTime
  updatedAt: DateTime
  deletedAt: DateTime
}

type Question {
  _id: ObjectID!
  originNumber: Int
  note: String
  text: String
  imageUrl: String
  videoUrl: String
  youtubeUrl: String
  questionItems: [QuestionItem]
  publishedAt: DateTime
  createdAt: DateTime
  createdBy: User
  updatedAt: DateTime
  deletedAt: DateTime
}

type QuestionItem {
  _id: ObjectID!
  key: String
  originNumber: Int
  text: String
  imageUrl: String
  videoUrl: String
  youtubeUrl: String
}

type QuestionTemplate {
  _id: ObjectID!
  originNumber: Int
  note: String
  text: String
  imageUrl: String
  videoUrl: String
  youtubeUrl: String
  questionTemplateItems: [QuestionTemplateItem]
  publishedAt: DateTime
  createdAt: DateTime
  updatedAt: DateTime
  deletedAt: DateTime
}

type QuestionTemplateItem {
  _id: ObjectID!
  key: String
  originNumber: Int
  text: String
  imageUrl: String
  videoUrl: String
  youtubeUrl: String
}

input QuestionItemInput {
  key: String
  originNumber: Int
  text: String
  imageUrl: String
  videoUrl: String
  youtubeUrl: String
}

input QuestionInput {
  originNumber: Int
  note: String
  text: String
  imageUrl: String
  videoUrl: String
  youtubeUrl: String
  questionItems: [QuestionItemInput]
}

input GroupQuestionInput {
  title: String
  description: String
  thumbnailUrl: String
  anyTime: Boolean
  startAt: DateTime
  endAt: DateTime
}

extend type Query {
  questions: [Question!]!
  groupQuestions: [GroupQuestion!]!
  findGroupQuestion(_id: String!): GroupQuestion!
}

extend type Mutation {
  createQuestion(input: QuestionInput!): Question!
  createGroupQuestion(input: GroupQuestionInput!): GroupQuestion!
}