scalar ObjectID
scalar DateTime

type Media {
  _id: ObjectID!
  type: String
  url: String
}

input MediaInput {
  _id: String
  type: String
  url: String
}

type Block {
  _id: ObjectID!
  label: String,
  text: String,
  media: Media,
  blocks: [Block]
}
input BlockInput {
  _id: String
  label: String,
  text: String,
  media: MediaInput,
  blocks: [BlockInput]
}

type Exam {
  _id: ObjectID!
  title: String
  description: String
  thumbnailUrl: String
  questions: [Question]
  answers: [Answer]
  anyTime: Boolean
  startAt: DateTime
  endAt: DateTime
  publishedAt: DateTime
  createdAt: DateTime
  createdBy: User
  updatedAt: DateTime
  updatedBy: User
  deletedAt: DateTime
  deletedBy: User
}

input ExamInput {
  title: String
  description: String
  thumbnailUrl: String
  anyTime: Boolean
  startAt: DateTime
  endAt: DateTime
}

type Answer {
  _id: ObjectID!
  user: User
  lock: Boolean
  questions: [Question]
  startAt: DateTime
  endAt: DateTime
}

type Question {
  _id: ObjectID!
  name: String
  note: String
  text: String
  media: Media
  options: [Block]
  correctOption: [Block]
  publishedAt: DateTime
  createdAt: DateTime
  createdBy: User
  updatedAt: DateTime
  updatedBy: User
  deletedAt: DateTime
  deletedBy: User
}
input QuestionInput {
  _id: String
  name: String
  note: String
  text: String
  media: MediaInput
  blocks: [BlockInput]
  options: [BlockInput]
  correctOption: [BlockInput]
}

type QuestionTemplate {
  _id: ObjectID!
  name: String
  note: String
  text: String
  media: Media
  blocks: [Block]
}

extend type Query {
  questionTemplates: [QuestionTemplate!]!
  exams: [Exam!]!
  findExam(_id: String!): Exam!
}

extend type Mutation {
  createExam(input: ExamInput!): Exam!
  addQuestionIntoExam(id: String!, input: QuestionInput!): Exam!
}