package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"
	"learning-server/graph/models"
	"learning-server/internal/db"

	"go.mongodb.org/mongo-driver/bson"
)

// CreateQuestion is the resolver for the createQuestion field.
func (r *mutationResolver) CreateQuestion(ctx context.Context, input models.NewQuestion) (*models.Question, error) {
	collection := db.GetCollection("questions")

	// Create a new question instance
	question := models.Question{
		ID:          bson.TypeObjectID.String(),
		Title:       input.Title,
		Description: input.Description,
	}
	fmt.Println(question)

	// Insert the question into the database
	_, err := collection.InsertOne(ctx, question)
	if err != nil {
		return nil, err
	}

	// Return the created question
	return &question, nil
}

// Questions is the resolver for the questions field.
func (r *queryResolver) Questions(ctx context.Context) ([]*models.Question, error) {
	panic(fmt.Errorf("not implemented: Questions - questions"))
}
