package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"
	"learning-server/entity"
	"learning-server/internal/db"
	"learning-server/internal/validation"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// User is the resolver for the user field.
func (r *answerResolver) User(ctx context.Context, obj *entity.Answer) (*entity.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// PublishedAt is the resolver for the publishedAt field.
func (r *answerResolver) PublishedAt(ctx context.Context, obj *entity.Answer) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: PublishedAt - publishedAt"))
}

// CreatedBy is the resolver for the createdBy field.
func (r *groupQuestionResolver) CreatedBy(ctx context.Context, obj *entity.GroupQuestion) (*entity.User, error) {
	panic(fmt.Errorf("not implemented: CreatedBy - createdBy"))
}

// CreateQuestion is the resolver for the createQuestion field.
func (r *mutationResolver) CreateQuestion(ctx context.Context, input entity.QuestionInput) (*entity.Question, error) {
	if err := validation.ValidateStruct(input); err != nil {
		return nil, fmt.Errorf("validation failed: %v", err)
	}

	questionItemsList := make([]entity.QuestionItemInput, len(input.QuestionItemInput))
	for i, input := range input.QuestionItemInput {
		questionItemsList[i] = entity.QuestionItemInput{
			ID:           bson.NewObjectID(),
			Key:          input.Key,
			OriginNumber: input.OriginNumber,
			Text:         input.Text,
			ImageUrl:     input.ImageUrl,
			VideoUrl:     input.VideoUrl,
			YoutubeUrl:   input.YoutubeUrl,
		}
	}

	questionInput := &entity.QuestionInput{
		ID:                bson.NewObjectID(),
		OriginNumber:      input.OriginNumber,
		Text:              input.Text,
		ImageUrl:          input.ImageUrl,
		VideoUrl:          input.VideoUrl,
		YoutubeUrl:        input.YoutubeUrl,
		QuestionItemInput: questionItemsList,
	}

	collection := db.GetCollection("questions")
	res, err := collection.InsertOne(ctx, questionInput)
	if err != nil {
		return nil, err
	}

	var question entity.Question
	filter := bson.M{"_id": res.InsertedID}
	err = collection.FindOne(ctx, filter).Decode(&question)
	if err != nil {
		return nil, err
	}

	return &question, nil
}

// CreateGroupQuestion is the resolver for the createGroupQuestion field.
func (r *mutationResolver) CreateGroupQuestion(ctx context.Context, input entity.GroupQuestionInput) (*entity.GroupQuestion, error) {
	if err := validation.ValidateStruct(input); err != nil {
		return nil, fmt.Errorf("validation failed: %v", err)
	}

	groupQuestionInput := &entity.GroupQuestionInput{
		Title:        input.Title,
		Description:  input.Description,
		ThumbnailUrl: input.ThumbnailUrl,
		AnyTime:      input.AnyTime,
		StartAt:      input.StartAt,
		EndAt:        input.EndAt,
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	}

	collection := db.GetCollection("questions")
	res, err := collection.InsertOne(ctx, groupQuestionInput)
	if err != nil {
		return nil, err
	}

	var groupQuestion entity.GroupQuestion
	filter := bson.M{"_id": res.InsertedID}
	err = collection.FindOne(ctx, filter).Decode(&groupQuestion)
	if err != nil {
		return nil, err
	}

	return &groupQuestion, nil
}

// Questions is the resolver for the questions field.
func (r *queryResolver) Questions(ctx context.Context) ([]*entity.Question, error) {
	collection := db.GetCollection("questions")
	cursor, err := collection.Find(ctx, bson.M{})

	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var questions []*entity.Question
	for cursor.Next(ctx) {
		var question entity.Question
		err := cursor.Decode(&question)
		if err != nil {
			return nil, err
		}
		questions = append(questions, &question)
	}

	return questions, nil
}

// GroupQuestions is the resolver for the groupQuestions field.
func (r *queryResolver) GroupQuestions(ctx context.Context) ([]*entity.GroupQuestion, error) {
	collection := db.GetCollection("questions")
	cursor, err := collection.Find(ctx, bson.M{})

	if err != nil {
		return nil, err
	}
	defer cursor.Close(ctx)

	var groupQuestions []*entity.GroupQuestion
	for cursor.Next(ctx) {
		var question entity.GroupQuestion
		err := cursor.Decode(&question)
		if err != nil {
			return nil, err
		}
		groupQuestions = append(groupQuestions, &question)
	}

	return groupQuestions, nil
}

// CreatedBy is the resolver for the createdBy field.
func (r *questionResolver) CreatedBy(ctx context.Context, obj *entity.Question) (*entity.User, error) {
	panic(fmt.Errorf("not implemented: CreatedBy - createdBy"))
}

// QuestionItems is the resolver for the questionItems field.
func (r *questionInputResolver) QuestionItems(ctx context.Context, obj *entity.QuestionInput, data []*entity.QuestionItemInput) error {
	panic(fmt.Errorf("not implemented: QuestionItems - questionItems"))
}

// Answer returns AnswerResolver implementation.
func (r *Resolver) Answer() AnswerResolver { return &answerResolver{r} }

// GroupQuestion returns GroupQuestionResolver implementation.
func (r *Resolver) GroupQuestion() GroupQuestionResolver { return &groupQuestionResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Question returns QuestionResolver implementation.
func (r *Resolver) Question() QuestionResolver { return &questionResolver{r} }

// QuestionInput returns QuestionInputResolver implementation.
func (r *Resolver) QuestionInput() QuestionInputResolver { return &questionInputResolver{r} }

type answerResolver struct{ *Resolver }
type groupQuestionResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type questionResolver struct{ *Resolver }
type questionInputResolver struct{ *Resolver }
