package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"
	"learning-server/graph/model"
)

// Person is the resolver for the person field.
func (r *queryResolver) Person(ctx context.Context) ([]*model.Person, error) {
	panic(fmt.Errorf("not implemented: Person - person"))
}

// Pet is the resolver for the pet field.
func (r *queryResolver) Pet(ctx context.Context) ([]*model.Pet, error) {
	panic(fmt.Errorf("not implemented: Pet - pet"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
