package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"
	"io"
	"learning-server/entity"

	"github.com/99designs/gqlgen/graphql"
	"go.mongodb.org/mongo-driver/v2/bson"
)

// SingleUpload is the resolver for the singleUpload field.
func (r *mutationResolver) SingleUpload(ctx context.Context, file graphql.Upload) (*entity.File, error) {
	content, err := io.ReadAll(file.File)
	if err != nil {
		return nil, err
	}
	return &entity.File{
		ID:   bson.NewObjectID(),
		Name: file.Filename,
		Type: string(content),
		Path: "",
		Url:  "",
	}, nil
}

// SingleUploadWithPayload is the resolver for the singleUploadWithPayload field.
func (r *mutationResolver) SingleUploadWithPayload(ctx context.Context, req entity.UploadFile) (*entity.File, error) {
	panic(fmt.Errorf("not implemented: SingleUploadWithPayload - singleUploadWithPayload"))
}

// MultipleUpload is the resolver for the multipleUpload field.
func (r *mutationResolver) MultipleUpload(ctx context.Context, files []*graphql.Upload) ([]*entity.File, error) {
	panic(fmt.Errorf("not implemented: MultipleUpload - multipleUpload"))
}

// MultipleUploadWithPayload is the resolver for the multipleUploadWithPayload field.
func (r *mutationResolver) MultipleUploadWithPayload(ctx context.Context, req []*entity.UploadFile) ([]*entity.File, error) {
	panic(fmt.Errorf("not implemented: MultipleUploadWithPayload - multipleUploadWithPayload"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
