package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"
	"learning-server/entity"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*entity.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *entity.User) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
